### ISSUE TITLE
[MM]: Team meeting

### ISSUE THREAD

**Issue by Grutschus** [Grutschus/human-fall-detection#2]
# Meeting Minutes from 2023-11-07

**Attendees:**
- Till
- Ola
- Emir

## Agenda
- Decide on the Dataset and Task definition to follow up #1 
- Define future Todos

## Notes
- Proposal from Ola
  - CAUCA Fall
  - UP Fall
  - Scenario:
      - Take the newer dataset (CAUCA Fall)
      - Take one of the existing models
  - Contribution:
    - Provide benchmarks of existing models on the CAUCA Fall

- Decision:
  - We opt for the following proposal:  Wrangle the High Quality Fall dataset and train an SOTA Temporal Action Localization algorithm on it to detect 3 classes: ADL, Falling, Lying

- Coming up
	- Continue our literature review
	- Set up the MMAction2 framework in our repo (Till)
	- Understand the dataset format required to work with MMAction2 (Ola)
	- Research and decision on the model that is most suitable for us (Emir)
	- Annotate the High Quality Fall dataset

## Follow-up / Summary / TODOs
- [x] Set up the MMAction2 framework in our repo #3 
- [ ] Understand and define the dataset format #4 
- [ ] Research SOTA models and decide on the most suitable for our task #5 
- [ ] Annotate the High Quality Fall dataset #6
